# Generated by Django 6.0.4 on 2026-04-15 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_classes', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='result',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.class'),
        ),
        migrations.AddField(
            model_name='result',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student'),
        ),
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='academics.class'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_classes', to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_level', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'subject', 'class_obj', 'term', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectclass',
            unique_together={('subject', 'class_obj')},
        ),
    ]
